#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Combobulator.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MINI_Combobulator")]
	public partial class CombobulatorDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTitle(Title instance);
    partial void UpdateTitle(Title instance);
    partial void DeleteTitle(Title instance);
    partial void InsertNewCar(NewCar instance);
    partial void UpdateNewCar(NewCar instance);
    partial void DeleteNewCar(NewCar instance);
    partial void InsertPostcodeLookUp(PostcodeLookUp instance);
    partial void UpdatePostcodeLookUp(PostcodeLookUp instance);
    partial void DeletePostcodeLookUp(PostcodeLookUp instance);
    partial void InsertDealer(Dealer instance);
    partial void UpdateDealer(Dealer instance);
    partial void DeleteDealer(Dealer instance);
    partial void InsertDealerLookUp(DealerLookUp instance);
    partial void UpdateDealerLookUp(DealerLookUp instance);
    partial void DeleteDealerLookUp(DealerLookUp instance);
    partial void InsertFinance(Finance instance);
    partial void UpdateFinance(Finance instance);
    partial void DeleteFinance(Finance instance);
    #endregion
		
		public CombobulatorDataContext() :
        base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CombobulatorConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CombobulatorDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CombobulatorDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CombobulatorDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CombobulatorDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Title> Titles
		{
			get
			{
				return this.GetTable<Title>();
			}
		}
		
		public System.Data.Linq.Table<NewCar> NewCars
		{
			get
			{
				return this.GetTable<NewCar>();
			}
		}
		
		public System.Data.Linq.Table<PostcodeLookUp> PostcodeLookUps
		{
			get
			{
				return this.GetTable<PostcodeLookUp>();
			}
		}
		
		public System.Data.Linq.Table<Dealer> Dealers
		{
			get
			{
				return this.GetTable<Dealer>();
			}
		}
		
		public System.Data.Linq.Table<DealerLookUp> DealerLookUps
		{
			get
			{
				return this.GetTable<DealerLookUp>();
			}
		}
		
		public System.Data.Linq.Table<Finance> Finances
		{
			get
			{
				return this.GetTable<Finance>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetTitles")]
		public ISingleResult<Title> GetTitles()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Title>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetLookups")]
		public ISingleResult<GetLookupsResult> GetLookups()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetLookupsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetPostCode")]
		public ISingleResult<GetPostCodeResult> GetPostCode([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string postcode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), postcode);
			return ((ISingleResult<GetPostCodeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetDealer")]
		public ISingleResult<GetDealerResult> GetDealer([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string postcode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), postcode);
			return ((ISingleResult<GetDealerResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetCarFinance")]
		public ISingleResult<GetCarFinanceResult> GetCarFinance([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NewCardId", DbType="Int")] System.Nullable<int> newCardId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), newCardId);
			return ((ISingleResult<GetCarFinanceResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetNewCar")]
		public ISingleResult<GetNewCarResult> GetNewCar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ModelCode", DbType="VarChar(10)")] string modelCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), modelCode);
			return ((ISingleResult<GetNewCarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetNewCars")]
		public ISingleResult<GetNewCarsResult> GetNewCars()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetNewCarsResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Titles")]
	public partial class Title : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public Title()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NewCars")]
	public partial class NewCar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Code;
		
		private string _Color;
		
		private string _Engine;
		
		private string _Name;
		
		private string _Capacity;
		
		private string _Luggage;
		
		private string _Lifestyle;
		
		private int _Awd;
		
		private int _High;
		
		private int _Convertible;
		
		private int _Price;
		
		private int _Cost;
		
		private int _Speed;
		
		private int _Mph;
		
		private int _Economy;
		
		private decimal _Mpg;
		
		private string _Alt1;
		
		private string _Alt2;
		
		private string _Alt3;
		
		private string _Terms;
		
		private EntitySet<Finance> _Finances;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnColorChanging(string value);
    partial void OnColorChanged();
    partial void OnEngineChanging(string value);
    partial void OnEngineChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCapacityChanging(string value);
    partial void OnCapacityChanged();
    partial void OnLuggageChanging(string value);
    partial void OnLuggageChanged();
    partial void OnLifestyleChanging(string value);
    partial void OnLifestyleChanged();
    partial void OnAwdChanging(int value);
    partial void OnAwdChanged();
    partial void OnHighChanging(int value);
    partial void OnHighChanged();
    partial void OnConvertibleChanging(int value);
    partial void OnConvertibleChanged();
    partial void OnPriceChanging(int value);
    partial void OnPriceChanged();
    partial void OnCostChanging(int value);
    partial void OnCostChanged();
    partial void OnSpeedChanging(int value);
    partial void OnSpeedChanged();
    partial void OnMphChanging(int value);
    partial void OnMphChanged();
    partial void OnEconomyChanging(int value);
    partial void OnEconomyChanged();
    partial void OnMpgChanging(decimal value);
    partial void OnMpgChanged();
    partial void OnAlt1Changing(string value);
    partial void OnAlt1Changed();
    partial void OnAlt2Changing(string value);
    partial void OnAlt2Changed();
    partial void OnAlt3Changing(string value);
    partial void OnAlt3Changed();
    partial void OnTermsChanging(string value);
    partial void OnTermsChanged();
    #endregion
		
		public NewCar()
		{
			this._Finances = new EntitySet<Finance>(new Action<Finance>(this.attach_Finances), new Action<Finance>(this.detach_Finances));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this.OnColorChanging(value);
					this.SendPropertyChanging();
					this._Color = value;
					this.SendPropertyChanged("Color");
					this.OnColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Engine", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Engine
		{
			get
			{
				return this._Engine;
			}
			set
			{
				if ((this._Engine != value))
				{
					this.OnEngineChanging(value);
					this.SendPropertyChanging();
					this._Engine = value;
					this.SendPropertyChanged("Engine");
					this.OnEngineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capacity", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Capacity
		{
			get
			{
				return this._Capacity;
			}
			set
			{
				if ((this._Capacity != value))
				{
					this.OnCapacityChanging(value);
					this.SendPropertyChanging();
					this._Capacity = value;
					this.SendPropertyChanged("Capacity");
					this.OnCapacityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Luggage", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Luggage
		{
			get
			{
				return this._Luggage;
			}
			set
			{
				if ((this._Luggage != value))
				{
					this.OnLuggageChanging(value);
					this.SendPropertyChanging();
					this._Luggage = value;
					this.SendPropertyChanged("Luggage");
					this.OnLuggageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lifestyle", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Lifestyle
		{
			get
			{
				return this._Lifestyle;
			}
			set
			{
				if ((this._Lifestyle != value))
				{
					this.OnLifestyleChanging(value);
					this.SendPropertyChanging();
					this._Lifestyle = value;
					this.SendPropertyChanged("Lifestyle");
					this.OnLifestyleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Awd", DbType="Int NOT NULL")]
		public int Awd
		{
			get
			{
				return this._Awd;
			}
			set
			{
				if ((this._Awd != value))
				{
					this.OnAwdChanging(value);
					this.SendPropertyChanging();
					this._Awd = value;
					this.SendPropertyChanged("Awd");
					this.OnAwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_High", DbType="Int NOT NULL")]
		public int High
		{
			get
			{
				return this._High;
			}
			set
			{
				if ((this._High != value))
				{
					this.OnHighChanging(value);
					this.SendPropertyChanging();
					this._High = value;
					this.SendPropertyChanged("High");
					this.OnHighChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Convertible", DbType="Int NOT NULL")]
		public int Convertible
		{
			get
			{
				return this._Convertible;
			}
			set
			{
				if ((this._Convertible != value))
				{
					this.OnConvertibleChanging(value);
					this.SendPropertyChanging();
					this._Convertible = value;
					this.SendPropertyChanged("Convertible");
					this.OnConvertibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Int NOT NULL")]
		public int Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost", DbType="Int NOT NULL")]
		public int Cost
		{
			get
			{
				return this._Cost;
			}
			set
			{
				if ((this._Cost != value))
				{
					this.OnCostChanging(value);
					this.SendPropertyChanging();
					this._Cost = value;
					this.SendPropertyChanged("Cost");
					this.OnCostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Speed", DbType="Int NOT NULL")]
		public int Speed
		{
			get
			{
				return this._Speed;
			}
			set
			{
				if ((this._Speed != value))
				{
					this.OnSpeedChanging(value);
					this.SendPropertyChanging();
					this._Speed = value;
					this.SendPropertyChanged("Speed");
					this.OnSpeedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mph", DbType="Int NOT NULL")]
		public int Mph
		{
			get
			{
				return this._Mph;
			}
			set
			{
				if ((this._Mph != value))
				{
					this.OnMphChanging(value);
					this.SendPropertyChanging();
					this._Mph = value;
					this.SendPropertyChanged("Mph");
					this.OnMphChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Economy", DbType="Int NOT NULL")]
		public int Economy
		{
			get
			{
				return this._Economy;
			}
			set
			{
				if ((this._Economy != value))
				{
					this.OnEconomyChanging(value);
					this.SendPropertyChanging();
					this._Economy = value;
					this.SendPropertyChanged("Economy");
					this.OnEconomyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mpg", DbType="Decimal(18,0) NOT NULL")]
		public decimal Mpg
		{
			get
			{
				return this._Mpg;
			}
			set
			{
				if ((this._Mpg != value))
				{
					this.OnMpgChanging(value);
					this.SendPropertyChanging();
					this._Mpg = value;
					this.SendPropertyChanged("Mpg");
					this.OnMpgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alt1", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Alt1
		{
			get
			{
				return this._Alt1;
			}
			set
			{
				if ((this._Alt1 != value))
				{
					this.OnAlt1Changing(value);
					this.SendPropertyChanging();
					this._Alt1 = value;
					this.SendPropertyChanged("Alt1");
					this.OnAlt1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alt2", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Alt2
		{
			get
			{
				return this._Alt2;
			}
			set
			{
				if ((this._Alt2 != value))
				{
					this.OnAlt2Changing(value);
					this.SendPropertyChanging();
					this._Alt2 = value;
					this.SendPropertyChanged("Alt2");
					this.OnAlt2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alt3", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Alt3
		{
			get
			{
				return this._Alt3;
			}
			set
			{
				if ((this._Alt3 != value))
				{
					this.OnAlt3Changing(value);
					this.SendPropertyChanging();
					this._Alt3 = value;
					this.SendPropertyChanged("Alt3");
					this.OnAlt3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Terms", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Terms
		{
			get
			{
				return this._Terms;
			}
			set
			{
				if ((this._Terms != value))
				{
					this.OnTermsChanging(value);
					this.SendPropertyChanging();
					this._Terms = value;
					this.SendPropertyChanged("Terms");
					this.OnTermsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NewCar_Finance", Storage="_Finances", ThisKey="Id", OtherKey="NewCarId")]
		public EntitySet<Finance> Finances
		{
			get
			{
				return this._Finances;
			}
			set
			{
				this._Finances.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Finances(Finance entity)
		{
			this.SendPropertyChanging();
			entity.NewCar = this;
		}
		
		private void detach_Finances(Finance entity)
		{
			this.SendPropertyChanging();
			entity.NewCar = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PostcodeLookUp")]
	public partial class PostcodeLookUp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _Address3;
		
		private string _Town;
		
		private string _County;
		
		private string _Postcode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnAddress1Changing(string value);
    partial void OnAddress1Changed();
    partial void OnAddress2Changing(string value);
    partial void OnAddress2Changed();
    partial void OnAddress3Changing(string value);
    partial void OnAddress3Changed();
    partial void OnTownChanging(string value);
    partial void OnTownChanged();
    partial void OnCountyChanging(string value);
    partial void OnCountyChanged();
    partial void OnPostcodeChanging(string value);
    partial void OnPostcodeChanged();
    #endregion
		
		public PostcodeLookUp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="NVarChar(MAX)")]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this.OnAddress1Changing(value);
					this.SendPropertyChanging();
					this._Address1 = value;
					this.SendPropertyChanged("Address1");
					this.OnAddress1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="NVarChar(MAX)")]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this.OnAddress2Changing(value);
					this.SendPropertyChanging();
					this._Address2 = value;
					this.SendPropertyChanged("Address2");
					this.OnAddress2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address3", DbType="NVarChar(MAX)")]
		public string Address3
		{
			get
			{
				return this._Address3;
			}
			set
			{
				if ((this._Address3 != value))
				{
					this.OnAddress3Changing(value);
					this.SendPropertyChanging();
					this._Address3 = value;
					this.SendPropertyChanged("Address3");
					this.OnAddress3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Town", DbType="NVarChar(50)")]
		public string Town
		{
			get
			{
				return this._Town;
			}
			set
			{
				if ((this._Town != value))
				{
					this.OnTownChanging(value);
					this.SendPropertyChanging();
					this._Town = value;
					this.SendPropertyChanged("Town");
					this.OnTownChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_County", DbType="NVarChar(50)")]
		public string County
		{
			get
			{
				return this._County;
			}
			set
			{
				if ((this._County != value))
				{
					this.OnCountyChanging(value);
					this.SendPropertyChanging();
					this._County = value;
					this.SendPropertyChanged("County");
					this.OnCountyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postcode", DbType="NVarChar(10)")]
		public string Postcode
		{
			get
			{
				return this._Postcode;
			}
			set
			{
				if ((this._Postcode != value))
				{
					this.OnPostcodeChanging(value);
					this.SendPropertyChanging();
					this._Postcode = value;
					this.SendPropertyChanged("Postcode");
					this.OnPostcodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dealer")]
	public partial class Dealer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _DealerLookUpId;
		
		private string _Postcode;
		
		private EntityRef<DealerLookUp> _DealerLookUp;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDealerLookUpIdChanging(int value);
    partial void OnDealerLookUpIdChanged();
    partial void OnPostcodeChanging(string value);
    partial void OnPostcodeChanged();
    #endregion
		
		public Dealer()
		{
			this._DealerLookUp = default(EntityRef<DealerLookUp>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DealerLookUpId", DbType="Int NOT NULL")]
		public int DealerLookUpId
		{
			get
			{
				return this._DealerLookUpId;
			}
			set
			{
				if ((this._DealerLookUpId != value))
				{
					if (this._DealerLookUp.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDealerLookUpIdChanging(value);
					this.SendPropertyChanging();
					this._DealerLookUpId = value;
					this.SendPropertyChanged("DealerLookUpId");
					this.OnDealerLookUpIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postcode", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Postcode
		{
			get
			{
				return this._Postcode;
			}
			set
			{
				if ((this._Postcode != value))
				{
					this.OnPostcodeChanging(value);
					this.SendPropertyChanging();
					this._Postcode = value;
					this.SendPropertyChanged("Postcode");
					this.OnPostcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DealerLookUp_Dealer", Storage="_DealerLookUp", ThisKey="DealerLookUpId", OtherKey="Id", IsForeignKey=true)]
		public DealerLookUp DealerLookUp
		{
			get
			{
				return this._DealerLookUp.Entity;
			}
			set
			{
				DealerLookUp previousValue = this._DealerLookUp.Entity;
				if (((previousValue != value) 
							|| (this._DealerLookUp.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DealerLookUp.Entity = null;
						previousValue.Dealers.Remove(this);
					}
					this._DealerLookUp.Entity = value;
					if ((value != null))
					{
						value.Dealers.Add(this);
						this._DealerLookUpId = value.Id;
					}
					else
					{
						this._DealerLookUpId = default(int);
					}
					this.SendPropertyChanged("DealerLookUp");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DealerLookUp")]
	public partial class DealerLookUp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _DealerId;
		
		private string _Name;
		
		private string _Address;
		
		private string _Country;
		
		private string _County;
		
		private string _Town;
		
		private string _Postcode;
		
		private System.Nullable<double> _Latitude;
		
		private System.Nullable<double> _Longitude;
		
		private string _Url;
		
		private string _Phone;
		
		private string _Fax;
		
		private System.Nullable<double> _Distance;
		
		private string _Email;
		
		private EntitySet<Dealer> _Dealers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDealerIdChanging(System.Nullable<int> value);
    partial void OnDealerIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnCountyChanging(string value);
    partial void OnCountyChanged();
    partial void OnTownChanging(string value);
    partial void OnTownChanged();
    partial void OnPostcodeChanging(string value);
    partial void OnPostcodeChanged();
    partial void OnLatitudeChanging(System.Nullable<double> value);
    partial void OnLatitudeChanged();
    partial void OnLongitudeChanging(System.Nullable<double> value);
    partial void OnLongitudeChanged();
    partial void OnUrlChanging(string value);
    partial void OnUrlChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    partial void OnDistanceChanging(System.Nullable<double> value);
    partial void OnDistanceChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public DealerLookUp()
		{
			this._Dealers = new EntitySet<Dealer>(new Action<Dealer>(this.attach_Dealers), new Action<Dealer>(this.detach_Dealers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DealerId", DbType="Int")]
		public System.Nullable<int> DealerId
		{
			get
			{
				return this._DealerId;
			}
			set
			{
				if ((this._DealerId != value))
				{
					this.OnDealerIdChanging(value);
					this.SendPropertyChanging();
					this._DealerId = value;
					this.SendPropertyChanged("DealerId");
					this.OnDealerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(MAX)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(MAX)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_County", DbType="NVarChar(MAX)")]
		public string County
		{
			get
			{
				return this._County;
			}
			set
			{
				if ((this._County != value))
				{
					this.OnCountyChanging(value);
					this.SendPropertyChanging();
					this._County = value;
					this.SendPropertyChanged("County");
					this.OnCountyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Town", DbType="NVarChar(MAX)")]
		public string Town
		{
			get
			{
				return this._Town;
			}
			set
			{
				if ((this._Town != value))
				{
					this.OnTownChanging(value);
					this.SendPropertyChanging();
					this._Town = value;
					this.SendPropertyChanged("Town");
					this.OnTownChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postcode", DbType="NVarChar(MAX)")]
		public string Postcode
		{
			get
			{
				return this._Postcode;
			}
			set
			{
				if ((this._Postcode != value))
				{
					this.OnPostcodeChanging(value);
					this.SendPropertyChanging();
					this._Postcode = value;
					this.SendPropertyChanged("Postcode");
					this.OnPostcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="Float")]
		public System.Nullable<double> Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this.OnLatitudeChanging(value);
					this.SendPropertyChanging();
					this._Latitude = value;
					this.SendPropertyChanged("Latitude");
					this.OnLatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="Float")]
		public System.Nullable<double> Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this.OnLongitudeChanging(value);
					this.SendPropertyChanging();
					this._Longitude = value;
					this.SendPropertyChanged("Longitude");
					this.OnLongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="NVarChar(MAX)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this.OnUrlChanging(value);
					this.SendPropertyChanging();
					this._Url = value;
					this.SendPropertyChanged("Url");
					this.OnUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(MAX)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="NVarChar(MAX)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Distance", DbType="Float")]
		public System.Nullable<double> Distance
		{
			get
			{
				return this._Distance;
			}
			set
			{
				if ((this._Distance != value))
				{
					this.OnDistanceChanging(value);
					this.SendPropertyChanging();
					this._Distance = value;
					this.SendPropertyChanged("Distance");
					this.OnDistanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(MAX)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DealerLookUp_Dealer", Storage="_Dealers", ThisKey="Id", OtherKey="DealerLookUpId")]
		public EntitySet<Dealer> Dealers
		{
			get
			{
				return this._Dealers;
			}
			set
			{
				this._Dealers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Dealers(Dealer entity)
		{
			this.SendPropertyChanging();
			entity.DealerLookUp = this;
		}
		
		private void detach_Dealers(Dealer entity)
		{
			this.SendPropertyChanging();
			entity.DealerLookUp = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Finances")]
	public partial class Finance : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _Term;
		
		private System.Nullable<double> _Payment;
		
		private System.Nullable<double> _FinancePrice;
		
		private System.Nullable<double> _Deposit;
		
		private System.Nullable<double> _Contribution;
		
		private System.Nullable<double> _PurchaseFee;
		
		private System.Nullable<double> _FinalPayment;
		
		private System.Nullable<double> _CreditCharge;
		
		private string _ROI;
		
		private string _APR;
		
		private System.Nullable<int> _NewCarId;
		
		private string _Info;
		
		private System.Nullable<double> _TotalAmount;
		
		private EntityRef<NewCar> _NewCar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTermChanging(System.Nullable<int> value);
    partial void OnTermChanged();
    partial void OnPaymentChanging(System.Nullable<double> value);
    partial void OnPaymentChanged();
    partial void OnFinancePriceChanging(System.Nullable<double> value);
    partial void OnFinancePriceChanged();
    partial void OnDepositChanging(System.Nullable<double> value);
    partial void OnDepositChanged();
    partial void OnContributionChanging(System.Nullable<double> value);
    partial void OnContributionChanged();
    partial void OnPurchaseFeeChanging(System.Nullable<double> value);
    partial void OnPurchaseFeeChanged();
    partial void OnFinalPaymentChanging(System.Nullable<double> value);
    partial void OnFinalPaymentChanged();
    partial void OnCreditChargeChanging(System.Nullable<double> value);
    partial void OnCreditChargeChanged();
    partial void OnROIChanging(string value);
    partial void OnROIChanged();
    partial void OnAPRChanging(string value);
    partial void OnAPRChanged();
    partial void OnNewCarIdChanging(System.Nullable<int> value);
    partial void OnNewCarIdChanged();
    partial void OnInfoChanging(string value);
    partial void OnInfoChanged();
    partial void OnTotalAmountChanging(System.Nullable<double> value);
    partial void OnTotalAmountChanged();
    #endregion
		
		public Finance()
		{
			this._NewCar = default(EntityRef<NewCar>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Term", DbType="Int")]
		public System.Nullable<int> Term
		{
			get
			{
				return this._Term;
			}
			set
			{
				if ((this._Term != value))
				{
					this.OnTermChanging(value);
					this.SendPropertyChanging();
					this._Term = value;
					this.SendPropertyChanged("Term");
					this.OnTermChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payment", DbType="Float")]
		public System.Nullable<double> Payment
		{
			get
			{
				return this._Payment;
			}
			set
			{
				if ((this._Payment != value))
				{
					this.OnPaymentChanging(value);
					this.SendPropertyChanging();
					this._Payment = value;
					this.SendPropertyChanged("Payment");
					this.OnPaymentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinancePrice", DbType="Float")]
		public System.Nullable<double> FinancePrice
		{
			get
			{
				return this._FinancePrice;
			}
			set
			{
				if ((this._FinancePrice != value))
				{
					this.OnFinancePriceChanging(value);
					this.SendPropertyChanging();
					this._FinancePrice = value;
					this.SendPropertyChanged("FinancePrice");
					this.OnFinancePriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deposit", DbType="Float")]
		public System.Nullable<double> Deposit
		{
			get
			{
				return this._Deposit;
			}
			set
			{
				if ((this._Deposit != value))
				{
					this.OnDepositChanging(value);
					this.SendPropertyChanging();
					this._Deposit = value;
					this.SendPropertyChanged("Deposit");
					this.OnDepositChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contribution", DbType="Float")]
		public System.Nullable<double> Contribution
		{
			get
			{
				return this._Contribution;
			}
			set
			{
				if ((this._Contribution != value))
				{
					this.OnContributionChanging(value);
					this.SendPropertyChanging();
					this._Contribution = value;
					this.SendPropertyChanged("Contribution");
					this.OnContributionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PurchaseFee", DbType="Float")]
		public System.Nullable<double> PurchaseFee
		{
			get
			{
				return this._PurchaseFee;
			}
			set
			{
				if ((this._PurchaseFee != value))
				{
					this.OnPurchaseFeeChanging(value);
					this.SendPropertyChanging();
					this._PurchaseFee = value;
					this.SendPropertyChanged("PurchaseFee");
					this.OnPurchaseFeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinalPayment", DbType="Float")]
		public System.Nullable<double> FinalPayment
		{
			get
			{
				return this._FinalPayment;
			}
			set
			{
				if ((this._FinalPayment != value))
				{
					this.OnFinalPaymentChanging(value);
					this.SendPropertyChanging();
					this._FinalPayment = value;
					this.SendPropertyChanged("FinalPayment");
					this.OnFinalPaymentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditCharge", DbType="Float")]
		public System.Nullable<double> CreditCharge
		{
			get
			{
				return this._CreditCharge;
			}
			set
			{
				if ((this._CreditCharge != value))
				{
					this.OnCreditChargeChanging(value);
					this.SendPropertyChanging();
					this._CreditCharge = value;
					this.SendPropertyChanged("CreditCharge");
					this.OnCreditChargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROI", DbType="NVarChar(50)")]
		public string ROI
		{
			get
			{
				return this._ROI;
			}
			set
			{
				if ((this._ROI != value))
				{
					this.OnROIChanging(value);
					this.SendPropertyChanging();
					this._ROI = value;
					this.SendPropertyChanged("ROI");
					this.OnROIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APR", DbType="NVarChar(50)")]
		public string APR
		{
			get
			{
				return this._APR;
			}
			set
			{
				if ((this._APR != value))
				{
					this.OnAPRChanging(value);
					this.SendPropertyChanging();
					this._APR = value;
					this.SendPropertyChanged("APR");
					this.OnAPRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewCarId", DbType="Int")]
		public System.Nullable<int> NewCarId
		{
			get
			{
				return this._NewCarId;
			}
			set
			{
				if ((this._NewCarId != value))
				{
					if (this._NewCar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNewCarIdChanging(value);
					this.SendPropertyChanging();
					this._NewCarId = value;
					this.SendPropertyChanged("NewCarId");
					this.OnNewCarIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Info", DbType="NVarChar(MAX)")]
		public string Info
		{
			get
			{
				return this._Info;
			}
			set
			{
				if ((this._Info != value))
				{
					this.OnInfoChanging(value);
					this.SendPropertyChanging();
					this._Info = value;
					this.SendPropertyChanged("Info");
					this.OnInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalAmount", DbType="Float")]
		public System.Nullable<double> TotalAmount
		{
			get
			{
				return this._TotalAmount;
			}
			set
			{
				if ((this._TotalAmount != value))
				{
					this.OnTotalAmountChanging(value);
					this.SendPropertyChanging();
					this._TotalAmount = value;
					this.SendPropertyChanged("TotalAmount");
					this.OnTotalAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NewCar_Finance", Storage="_NewCar", ThisKey="NewCarId", OtherKey="Id", IsForeignKey=true)]
		public NewCar NewCar
		{
			get
			{
				return this._NewCar.Entity;
			}
			set
			{
				NewCar previousValue = this._NewCar.Entity;
				if (((previousValue != value) 
							|| (this._NewCar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NewCar.Entity = null;
						previousValue.Finances.Remove(this);
					}
					this._NewCar.Entity = value;
					if ((value != null))
					{
						value.Finances.Add(this);
						this._NewCarId = value.Id;
					}
					else
					{
						this._NewCarId = default(Nullable<int>);
					}
					this.SendPropertyChanged("NewCar");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GetLookupsResult
	{
		
		private int _Id;
		
		private string _Name;
		
		public GetLookupsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(10)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	public partial class GetPostCodeResult
	{
		
		private int _Id;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _Address3;
		
		private string _Town;
		
		private string _County;
		
		private string _Postcode;
		
		public GetPostCodeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="NVarChar(50)")]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this._Address1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="NVarChar(50)")]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this._Address2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address3", DbType="NVarChar(50)")]
		public string Address3
		{
			get
			{
				return this._Address3;
			}
			set
			{
				if ((this._Address3 != value))
				{
					this._Address3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Town", DbType="NVarChar(50)")]
		public string Town
		{
			get
			{
				return this._Town;
			}
			set
			{
				if ((this._Town != value))
				{
					this._Town = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_County", DbType="NVarChar(50)")]
		public string County
		{
			get
			{
				return this._County;
			}
			set
			{
				if ((this._County != value))
				{
					this._County = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postcode", DbType="NVarChar(50)")]
		public string Postcode
		{
			get
			{
				return this._Postcode;
			}
			set
			{
				if ((this._Postcode != value))
				{
					this._Postcode = value;
				}
			}
		}
	}
	
	public partial class GetDealerResult
	{
		
		private int _Id;
		
		private System.Nullable<int> _DealerId;
		
		private string _Name;
		
		private string _Address;
		
		private string _Country;
		
		private string _County;
		
		private string _Town;
		
		private string _Postcode;
		
		private System.Nullable<double> _Latitude;
		
		private System.Nullable<double> _Longitude;
		
		private string _Url;
		
		private string _Phone;
		
		private string _Fax;
		
		private System.Nullable<double> _Distance;
		
		private string _Email;
		
		public GetDealerResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DealerId", DbType="Int")]
		public System.Nullable<int> DealerId
		{
			get
			{
				return this._DealerId;
			}
			set
			{
				if ((this._DealerId != value))
				{
					this._DealerId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(MAX)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(MAX)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this._Country = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_County", DbType="NVarChar(MAX)")]
		public string County
		{
			get
			{
				return this._County;
			}
			set
			{
				if ((this._County != value))
				{
					this._County = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Town", DbType="NVarChar(MAX)")]
		public string Town
		{
			get
			{
				return this._Town;
			}
			set
			{
				if ((this._Town != value))
				{
					this._Town = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postcode", DbType="NVarChar(MAX)")]
		public string Postcode
		{
			get
			{
				return this._Postcode;
			}
			set
			{
				if ((this._Postcode != value))
				{
					this._Postcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="Float")]
		public System.Nullable<double> Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this._Latitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="Float")]
		public System.Nullable<double> Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this._Longitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="NVarChar(MAX)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this._Url = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(MAX)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this._Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="NVarChar(MAX)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this._Fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Distance", DbType="Float")]
		public System.Nullable<double> Distance
		{
			get
			{
				return this._Distance;
			}
			set
			{
				if ((this._Distance != value))
				{
					this._Distance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(MAX)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
	}
	
	public partial class GetCarFinanceResult
	{
		
		private int _Id;
		
		private System.Nullable<int> _Term;
		
		private System.Nullable<double> _Payment;
		
		private System.Nullable<double> _FinancePrice;
		
		private System.Nullable<double> _Deposit;
		
		private System.Nullable<double> _Contribution;
		
		private System.Nullable<double> _PurchaseFee;
		
		private System.Nullable<double> _FinalPayment;
		
		private System.Nullable<double> _CreditCharge;
		
		private string _ROI;
		
		private string _APR;
		
		private System.Nullable<int> _NewCarId;
		
		private string _Info;
		
		private System.Nullable<double> _TotalAmount;
		
		public GetCarFinanceResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Term", DbType="Int")]
		public System.Nullable<int> Term
		{
			get
			{
				return this._Term;
			}
			set
			{
				if ((this._Term != value))
				{
					this._Term = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payment", DbType="Float")]
		public System.Nullable<double> Payment
		{
			get
			{
				return this._Payment;
			}
			set
			{
				if ((this._Payment != value))
				{
					this._Payment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinancePrice", DbType="Float")]
		public System.Nullable<double> FinancePrice
		{
			get
			{
				return this._FinancePrice;
			}
			set
			{
				if ((this._FinancePrice != value))
				{
					this._FinancePrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deposit", DbType="Float")]
		public System.Nullable<double> Deposit
		{
			get
			{
				return this._Deposit;
			}
			set
			{
				if ((this._Deposit != value))
				{
					this._Deposit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contribution", DbType="Float")]
		public System.Nullable<double> Contribution
		{
			get
			{
				return this._Contribution;
			}
			set
			{
				if ((this._Contribution != value))
				{
					this._Contribution = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PurchaseFee", DbType="Float")]
		public System.Nullable<double> PurchaseFee
		{
			get
			{
				return this._PurchaseFee;
			}
			set
			{
				if ((this._PurchaseFee != value))
				{
					this._PurchaseFee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinalPayment", DbType="Float")]
		public System.Nullable<double> FinalPayment
		{
			get
			{
				return this._FinalPayment;
			}
			set
			{
				if ((this._FinalPayment != value))
				{
					this._FinalPayment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditCharge", DbType="Float")]
		public System.Nullable<double> CreditCharge
		{
			get
			{
				return this._CreditCharge;
			}
			set
			{
				if ((this._CreditCharge != value))
				{
					this._CreditCharge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROI", DbType="NVarChar(50)")]
		public string ROI
		{
			get
			{
				return this._ROI;
			}
			set
			{
				if ((this._ROI != value))
				{
					this._ROI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APR", DbType="NVarChar(50)")]
		public string APR
		{
			get
			{
				return this._APR;
			}
			set
			{
				if ((this._APR != value))
				{
					this._APR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewCarId", DbType="Int")]
		public System.Nullable<int> NewCarId
		{
			get
			{
				return this._NewCarId;
			}
			set
			{
				if ((this._NewCarId != value))
				{
					this._NewCarId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Info", DbType="NVarChar(MAX)")]
		public string Info
		{
			get
			{
				return this._Info;
			}
			set
			{
				if ((this._Info != value))
				{
					this._Info = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalAmount", DbType="Float")]
		public System.Nullable<double> TotalAmount
		{
			get
			{
				return this._TotalAmount;
			}
			set
			{
				if ((this._TotalAmount != value))
				{
					this._TotalAmount = value;
				}
			}
		}
	}
	
	public partial class GetNewCarResult
	{
		
		private int _Id;
		
		private string _Code;
		
		private string _Color;
		
		private string _Engine;
		
		private string _Name;
		
		private string _Capacity;
		
		private string _Luggage;
		
		private string _Lifestyle;
		
		private int _Awd;
		
		private int _High;
		
		private int _Convertible;
		
		private int _Price;
		
		private int _Cost;
		
		private int _Speed;
		
		private int _Mph;
		
		private int _Economy;
		
		private decimal _Mpg;
		
		private string _Alt1;
		
		private string _Alt2;
		
		private string _Alt3;
		
		private string _Terms;
		
		public GetNewCarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this._Color = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Engine", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Engine
		{
			get
			{
				return this._Engine;
			}
			set
			{
				if ((this._Engine != value))
				{
					this._Engine = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capacity", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Capacity
		{
			get
			{
				return this._Capacity;
			}
			set
			{
				if ((this._Capacity != value))
				{
					this._Capacity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Luggage", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Luggage
		{
			get
			{
				return this._Luggage;
			}
			set
			{
				if ((this._Luggage != value))
				{
					this._Luggage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lifestyle", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Lifestyle
		{
			get
			{
				return this._Lifestyle;
			}
			set
			{
				if ((this._Lifestyle != value))
				{
					this._Lifestyle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Awd", DbType="Int NOT NULL")]
		public int Awd
		{
			get
			{
				return this._Awd;
			}
			set
			{
				if ((this._Awd != value))
				{
					this._Awd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_High", DbType="Int NOT NULL")]
		public int High
		{
			get
			{
				return this._High;
			}
			set
			{
				if ((this._High != value))
				{
					this._High = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Convertible", DbType="Int NOT NULL")]
		public int Convertible
		{
			get
			{
				return this._Convertible;
			}
			set
			{
				if ((this._Convertible != value))
				{
					this._Convertible = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Int NOT NULL")]
		public int Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost", DbType="Int NOT NULL")]
		public int Cost
		{
			get
			{
				return this._Cost;
			}
			set
			{
				if ((this._Cost != value))
				{
					this._Cost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Speed", DbType="Int NOT NULL")]
		public int Speed
		{
			get
			{
				return this._Speed;
			}
			set
			{
				if ((this._Speed != value))
				{
					this._Speed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mph", DbType="Int NOT NULL")]
		public int Mph
		{
			get
			{
				return this._Mph;
			}
			set
			{
				if ((this._Mph != value))
				{
					this._Mph = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Economy", DbType="Int NOT NULL")]
		public int Economy
		{
			get
			{
				return this._Economy;
			}
			set
			{
				if ((this._Economy != value))
				{
					this._Economy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mpg", DbType="Decimal(18,0) NOT NULL")]
		public decimal Mpg
		{
			get
			{
				return this._Mpg;
			}
			set
			{
				if ((this._Mpg != value))
				{
					this._Mpg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alt1", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Alt1
		{
			get
			{
				return this._Alt1;
			}
			set
			{
				if ((this._Alt1 != value))
				{
					this._Alt1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alt2", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Alt2
		{
			get
			{
				return this._Alt2;
			}
			set
			{
				if ((this._Alt2 != value))
				{
					this._Alt2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alt3", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Alt3
		{
			get
			{
				return this._Alt3;
			}
			set
			{
				if ((this._Alt3 != value))
				{
					this._Alt3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Terms", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Terms
		{
			get
			{
				return this._Terms;
			}
			set
			{
				if ((this._Terms != value))
				{
					this._Terms = value;
				}
			}
		}
	}
	
	public partial class GetNewCarsResult
	{
		
		private int _Id;
		
		private string _Code;
		
		private string _Color;
		
		private string _Engine;
		
		private string _Name;
		
		private string _Capacity;
		
		private string _Luggage;
		
		private string _Lifestyle;
		
		private int _Awd;
		
		private int _High;
		
		private int _Convertible;
		
		private int _Price;
		
		private int _Cost;
		
		private int _Speed;
		
		private int _Mph;
		
		private int _Economy;
		
		private decimal _Mpg;
		
		private string _Alt1;
		
		private string _Alt2;
		
		private string _Alt3;
		
		private string _Terms;
		
		public GetNewCarsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this._Color = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Engine", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Engine
		{
			get
			{
				return this._Engine;
			}
			set
			{
				if ((this._Engine != value))
				{
					this._Engine = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capacity", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Capacity
		{
			get
			{
				return this._Capacity;
			}
			set
			{
				if ((this._Capacity != value))
				{
					this._Capacity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Luggage", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Luggage
		{
			get
			{
				return this._Luggage;
			}
			set
			{
				if ((this._Luggage != value))
				{
					this._Luggage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lifestyle", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Lifestyle
		{
			get
			{
				return this._Lifestyle;
			}
			set
			{
				if ((this._Lifestyle != value))
				{
					this._Lifestyle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Awd", DbType="Int NOT NULL")]
		public int Awd
		{
			get
			{
				return this._Awd;
			}
			set
			{
				if ((this._Awd != value))
				{
					this._Awd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_High", DbType="Int NOT NULL")]
		public int High
		{
			get
			{
				return this._High;
			}
			set
			{
				if ((this._High != value))
				{
					this._High = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Convertible", DbType="Int NOT NULL")]
		public int Convertible
		{
			get
			{
				return this._Convertible;
			}
			set
			{
				if ((this._Convertible != value))
				{
					this._Convertible = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Int NOT NULL")]
		public int Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost", DbType="Int NOT NULL")]
		public int Cost
		{
			get
			{
				return this._Cost;
			}
			set
			{
				if ((this._Cost != value))
				{
					this._Cost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Speed", DbType="Int NOT NULL")]
		public int Speed
		{
			get
			{
				return this._Speed;
			}
			set
			{
				if ((this._Speed != value))
				{
					this._Speed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mph", DbType="Int NOT NULL")]
		public int Mph
		{
			get
			{
				return this._Mph;
			}
			set
			{
				if ((this._Mph != value))
				{
					this._Mph = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Economy", DbType="Int NOT NULL")]
		public int Economy
		{
			get
			{
				return this._Economy;
			}
			set
			{
				if ((this._Economy != value))
				{
					this._Economy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mpg", DbType="Decimal(18,0) NOT NULL")]
		public decimal Mpg
		{
			get
			{
				return this._Mpg;
			}
			set
			{
				if ((this._Mpg != value))
				{
					this._Mpg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alt1", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Alt1
		{
			get
			{
				return this._Alt1;
			}
			set
			{
				if ((this._Alt1 != value))
				{
					this._Alt1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alt2", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Alt2
		{
			get
			{
				return this._Alt2;
			}
			set
			{
				if ((this._Alt2 != value))
				{
					this._Alt2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alt3", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Alt3
		{
			get
			{
				return this._Alt3;
			}
			set
			{
				if ((this._Alt3 != value))
				{
					this._Alt3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Terms", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Terms
		{
			get
			{
				return this._Terms;
			}
			set
			{
				if ((this._Terms != value))
				{
					this._Terms = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
