<?xml version="1.0" encoding="utf-8"?><Database Name="MINI_Combobulator" Class="CombobulatorDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=JUSTFORKIX;Initial Catalog=MINI_Combobulator;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MINI_CombobulatorConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Cars" Member="Cars">
    <Type Name="Car" Id="ID1">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ModelCode" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Colour" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Engine" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CapacityScale" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LuggageScale" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Options" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PriceScale" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Cost" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PerformanceScale" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MPH" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EconomyScale" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MPG" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UsageScale" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Alt1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Alt2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Alt3" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TermsConditions" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Titles" Member="Titles">
    <Type Name="Title" Id="ID2">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Dealers" Member="Dealers">
    <Type Name="Dealer" Id="ID3">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NewCars" Member="NewCars">
    <Type Name="NewCar">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Color" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Engine" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Capacity" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Luggage" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Lifestyle" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Awd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="High" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Convertible" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cost" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Speed" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mph" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Economy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mpg" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Alt1" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Alt2" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Alt3" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Terms" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="NewCar_Finance" Member="Finances" ThisKey="Id" OtherKey="NewCarId" Type="Finance" />
    </Type>
  </Table>
  <Table Name="dbo.PostcodeLookUp" Member="PostcodeLookUps">
    <Type Name="PostcodeLookUp">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Address1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Town" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="County" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Postcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Finances" Member="Finances">
    <Type Name="Finance">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Term" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Payment" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FinancePrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Deposit" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Contribution" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PurchaseFee" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FinalPayment" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CreditCharge" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ROI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="APR" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NewCarId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Info" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="NewCar_Finance" Member="NewCar" ThisKey="NewCarId" OtherKey="Id" Type="NewCar" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetCar" Method="GetCar">
    <Parameter Name="ModelCode" Parameter="modelCode" Type="System.String" DbType="VarChar(10)" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.GetCars" Method="GetCars">
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.GetTitles" Method="GetTitles">
    <ElementType IdRef="ID2" />
  </Function>
  <Function Name="dbo.GetDealers" Method="GetDealers">
    <ElementType IdRef="ID3" />
  </Function>
  <Function Name="dbo.GetLookups" Method="GetLookups">
    <ElementType Name="GetLookupsResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetCarFinance" Method="GetCarFinance">
    <Parameter Name="NewCardId" Parameter="newCardId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetCarFinanceResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Term" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Payment" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FinancePrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Deposit" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Contribution" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PurchaseFee" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FinalPayment" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CreditCharge" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ROI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="APR" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NewCarId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Info" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetNewCar" Method="GetNewCar">
    <Parameter Name="ModelCode" Parameter="modelCode" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="GetNewCarResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Color" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Engine" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Capacity" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Luggage" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Lifestyle" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Awd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="High" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Convertible" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cost" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Speed" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mph" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Economy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mpg" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Alt1" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Alt2" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Alt3" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Terms" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetNewCars" Method="GetNewCars">
    <ElementType Name="GetNewCarsResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Color" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Engine" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Capacity" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Luggage" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Lifestyle" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Awd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="High" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Convertible" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cost" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Speed" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mph" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Economy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mpg" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Alt1" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Alt2" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Alt3" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Terms" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetPostCode" Method="GetPostCode">
    <Parameter Name="postcode" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="GetPostCodeResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Address1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Town" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="County" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Postcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>